kind: Deployment
apiVersion: apps/v1
metadata:
  name: "{{ .Values.name }}"
  namespace: app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: "{{ .Values.name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.name }}"
    spec:
      containers:
        - name: "{{ .Values.name }}"
          image: "{{ .Values.deployment.image }}"
          ports:
            - containerPort: {{ .Values.deployment.containerPort }}
          imagePullPolicy: IfNotPresent
          command: ["npm","run","dev"]                                               



# apiVersion: extensions/v1beta1
# kind: Deployment
# metadata:
#   name: whoami-deployment
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: whoami
#   template:
#     metadata:
#       labels:
#         app: whoami
#     spec:
#       containers:
#       - name: whoami-container
#         image: containous/whoami
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: whoami-service
# spec:
#   ports:
#   - name: http
#     targetPort: 80
#     port: 80
#   selector:
#     app: whoami